version: "3.8"

services:
  movies_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - bridge-network
    restart: unless-stopped
    volumes:
      - /app/node_modules 

networks:
  bridge-network:
    driver: bridge
